name: decript the file
on: [push]

jobs:
  decrypt: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v1
      - name: Decrpt file
        run: gpg --quiet --batch --yes --decrypt --passphrase="$PASSPHARES" --output $HOME/secret.json secret.json.gpg
        env: 
          PASSPHARES: ${{secrets.PASSPHARES}}
      - name : print file contect
        run: cat $HOME/secret.json