name: list path and file within input
on: [push]
jobs:
  list-path:
    runs-on: ubuntu-latest
    steps:
      - name: Before checkout listfiles
        run: |
          pwd
          ls -a
      - name: checkout test # this will act on the keyword action--> CHECK OUT TO SPECIFIC COMMIT
        # instead of run use the "uses" keyword which will fetch the repo/user and assing it to your on going commit
        # uses: actions/yourrepo_name
        uses: actions/checkout@v1
      - name: After checkout listfiles
        run: |
          pwd
          ls -a
      - name: Fetch some enviornment variable
      # $GITHUB_SHA  --> Return UserID
      # $GITHUB_REPOSITORY  --> Return Repo name
      # $GITHUB_WORKSPACE --> Return WorkSpace name
      # $github.token --> Return Token of the account
        run: |
          pwd
          ls -a 
          echo $GITHUB_SHA    
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{github.token}}" 
