name: inclued  and exclude in matrix
on: ['push']
jobs:
  node-version:
    strategy:
      matrix:
        os: [macos-latest,ubuntu-latest,windows-latest]
        node_version: [6,7]   # so now total number of run will be 6 every os with every node version
        include:
          - os: macos-latest
            node-verion: 7
            in_mac_7: "Yes Sagar!"
        exclude: 
          - os: ubuntu-latest
            node-version: 7
          - os: windows-latest
            node-version: 6
    env: 
      in_mac_7: ${{matrix.in_mac_7}}
    runs-on: ${{matrix.os}}
    steps:
      - name: log node node-version 
        run: node -v 
      - uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.nodeversion}}
      - name: log node node-version
        run: |
          node -v
          echo $in_mac_7