name: Action on pull request
on: [pull_request]

jobs:
  actOnPullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: actNow on pull
        run: echo "This is run when the pull request submission happened"
